name: Progect1
version: '${project.version}'
main: me.smudgg.progect1.Progect1
api-version: 1.17
authors: [ Smudge ]
commands:
  psetpoints:
    description: Sets points
    usage: /<command> <points>
  paddpoints:
    description: Adds points
    usage: /<command> <points>
  preload:
    description: Reloads configs
    usage: /<command>
  ppoints:
    description: Shows Points
    usage: /<command>